---[[
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuyan.
--- DateTime: 2018/9/24 15:36
---]]

local Bullet = class("Bullet", function()
    return cc.Sprite:create()
end)

local size = cc.Director:getInstance():getWinSize()
local array = {}

function Bullet.create(spriteFrameName)
    local bullet = Bullet.new(spriteFrameName)
    return bullet
end

function Bullet:ctor(spriteFrameName)
    self:setSpriteFrame(spriteFrameName)
    self:setVisible(false)
    self.velocity = Sprite_Velocity.Bullet

    local body = cc.PhysicsBody:createBox(self:getContentSize(),cc.PHYSICSBODY_MATERIAL_DEFAULT,cc.p(0,0))
    
    body:setCategoryBitmask(0x01)
    body:setCollisionBitmask(0x02)
    body:setContactTestBitmask(0x01)

    self:setPhysicsBody(body)

    function onNodeEvent(tag)
        if tag == "exit" then
            self:unscheduleUpdate()
        end
    end

    self:registerScriptHandler(onNodeEvent)
end

function Bullet:showBulletFromFighter(fighter)
    local fighterX, fighterY = fighter:getPosition()
    self:setPosition(cc.p(fighterX, fighterY + fighter:getContentSize().height / 4))
    self:setVisible(true)
     
    
    function update(dt)
        self.x, self.y = self:getPosition()

        self:setPosition(cc.p(self.x + self.velocity.x * dt, self.y + self.velocity.y * dt))
         -- table.insert(array,self)
---子弹超出屏幕外
        if self.y > size.height then
            self:setVisible(false)
    
            self:unscheduleUpdate()

            -- array = {}
            -- self:destroy()
        end
    end

   
    self:scheduleUpdateWithPriorityLua(update, 0)
end
--  function Bullet:destroy(  )
--      -- body
--      for k, v in pairs(array) do
--         table.remove(array, k)
    
-- end
 -- end
return Bullet


